### ISSUE TITLE
Adding user option to automatically clear storage

### ISSUE THREAD

**Issue by gwaygenomics** [greenelab/staNMF#2]
We discussed a potential bottleneck in staNMF usage - the fact that it requires storage of potentially very large intermediate files. We also discussed potential mitigation strategies including using _temporary files_ from the [`tempfile` package](https://docs.python.org/3/library/tempfile.html) and allowing a user to control how and where the intermediate files are saved or not.

**Comment by gwaygenomics** [comment]
Looks like #11 adds this enhancement. Good to close the issue?

**Comment by amyecampbell** [comment]
Yeah! Though my solution was much simpler (and less adaptable to different needs, really) than using tempfile. Should I keep it open for when I add the tempfile enhancement? Or close it for now and make an issue that's to update the function to that?

**Comment by gwaygenomics** [comment]
up to you! I think you successfully addressed the user option to clear storage
